### ISSUE TITLE
Vertaisarviointi välipalautuksesta 2

### ISSUE THREAD

**Issue by T-Marenk** [ounisk/TSOHA_harjoitustyo#1]
Koodi on selkeää ja helppoa lukea. Se on jaettu järkeviin osiin eri tiedostoihin, josta sitä voi lukea ja ymmärtää helposti ja nopeasti, mitä eri osat tekevät. 

Sovellus näyttää mukavalta ja selkeä käyttöiseltä, siitä mitä sitä pystyi näkemään. Eri värit lisätty linkkeihin ja muualle sivulle antavat mukavuuden tunnetta sovellusta käyttäessä. Sovellus ei myöskään vaikuta monimutkaiselta ja on hyvin nopea ymmärtää, mitä pitää tehdä, jotta saa asioita tehtyä.

Sovelluksen ollessa vielä hyvin alkuvaiheessa, on sitä vielä vaikea testata. Testatuista asioista kuitenkin suosittelisin lisäämään mahdollisuuden palata rekisteröitymissivulta etusivulle tai kirjautumiseen sekä virheviesteistä antaa mahdollisuus palata rekisteröitymiseen tai kirjautumiseen, esim "salasana ei täsmää" sivulta ei pääse minnekkään ilman nettiselaimen omaa takanappia, mikä ei ole hyvä kokemus käyttäjälle tällä hetkellä. 

Käyttäjän rekisteröityminen onnistuu, mutta sisäänkirjautuminen tuottaa Internal server error virheen. En pystynyt itse huomaamaan, missä virhe tulee, mutta pystyn hyvin varmasti sanomaan virheen olevan jossain onnistuneen kirjautumisen yhteydessä

**Comment by ounisk** [comment]
Kiitos palautteesta!
